### ISSUE TITLE
Replace reference genome field with TaxID organism

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#10]
We should remove the reference genome field and replace it with an entry from the [NCBI Taxonomy](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7408187/) resource.

The relevant information to store in MaveDB is:

- Taxonomy ID
- Species name
- Common name

We will want to prepopulate the database with relevant Taxonomy IDs and also allow users to enter a different valid Taxonomy ID if needed.

When a new Taxonomy ID is entered, the backend should fetch the details using an eutils API call and display the organism name in the form preview. We can create a new entry in the database once the dataset is submitted. This information can be retrieved using the [NCBI Datasets REST API](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/rest-api/).

The field in the website UI should be able to autocomplete based on the current name, common name, or TaxID. The API should accept the current name, common name, or TaxID as exact matches (see the [entry for human](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=9606&lvl=3&lin=f&keep=1&srchmode=1&unlock) as an example - an API call should be able to provide "human" instead of "9606").

For synthetic sequences, we need to find out if Taxonomy has a suitable term for this, or if we need to define our own special term that's MaveDB-specific.

We can handle this issue in two steps:

- [ ] Replace the Reference Genome model with a Target Organism model
- [ ] Add support for adding new Target Organisms

**Comment by afrubin** [comment]
An additional clarification here is that this change should also get rid of the `'reference_maps'` list, since that's quite clumsy and each target should only have one TaxID.

**Comment by afrubin** [comment]
@EstelleDa Here are files with the tax_id structures we want to store in the database (as JSON) and the tax_ids for each published score set target in the database.
[published_score_set_tax_ids.csv](https://github.com/VariantEffect/mavedb-api/files/11741659/published_score_set_tax_ids.csv)
[mavedb_taxon_objects.json.txt](https://github.com/VariantEffect/mavedb-api/files/11741660/mavedb_taxon_objects.json.txt)

**Comment by jstone-uw** [comment]
Released in version 2024.0.0 on 2024-04-15.
