### ISSUE TITLE
Uniqueness should be enforced on URNs at schema level.

### ISSUE THREAD

**Issue by ashsny** [VariantEffect/mavedb-api#100]
This is true for all models with a URN, namely experiments, experiment_sets, score_sets, and variants. 

This would prevent problems like https://github.com/VariantEffect/MaveDB/issues/197 (though admittedly, that would have been prevented with a repeated? 500 at publish time without an understandable error message, which is not ideal).

**Comment by nickzoic** [comment]
yep, a 500 at publish time isn't great but maybe that's better than it appearing to be successful ... retrying on the constraint is also a good way to avoid race conditions on assigning a new URN.

**Comment by ashsny** [comment]
fixed by #102
