### ISSUE TITLE
Main branch Dashboard doesn't show any score sets that do not have an associated target gene.

### ISSUE THREAD

**Issue by EstelleDa** [VariantEffect/mavedb-api#111]
`search_score_sets` function of src/mavedb/lib/score_sets.py doesn't return any score set.

It leads to dashboard is empty.

Problem is from
```
score_sets: list[ScoreSet] = (
        query.join(ScoreSet.experiment).join(ScoreSet.target_genes).order_by(Experiment.title).all()
    )
```
Model `ScoreSet` doesn't have `target_genes` attribute.

**Comment by ashsny** [comment]
I don't think that function/line is the problem. As best I can tell, it is invoked in every scoreset search (including working pages like https://mavedb.org/#/search?search=HSP90) etc. What makes you think it is that line?

**Comment by EstelleDa** [comment]
`search_my_score_sets` calls `_search_score_sets`. There isn't any `search` so the `query` only filters `owner_id`. `Query` looks Ok or maybe here gets problem. Then the next codes are `query.join` part. On my side `ScoreSet.target_genes` shows "Cannot find declaration to go to" and the returned `score_sets` is empty. That's why I think this part leads to the problem.

It's interesting that search page is totally fine and the returned `score_sets` isn't empty. It seems the `query.join` is OK.

I might miss something. The problem description is what I currently found. It may not lead to actual problem.

**Comment by ashsny** [comment]
I am able to show some scoresets in my dashboard in a dev environment with mavedb-api and mavedb-ui at current main by setting some scoresets to be created by me in my dev database like so:
```
UPDATE "public"."scoresets" SET "created_by_id" = 9999 WHERE "id" = 24;
UPDATE "public"."scoresets" SET "created_by_id" = 9999 WHERE "id" = 25;
UPDATE "public"."scoresets" SET "created_by_id" = 9999 WHERE "id" = 26;
UPDATE "public"."scoresets" SET "created_by_id" = 9999 WHERE "id" = 27;
UPDATE "public"."experiments" SET "created_by_id" = 9999 WHERE "id" = 12;
UPDATE "public"."experiments" SET "created_by_id" = 9999 WHERE "id" = 13;
UPDATE "public"."experiments" SET "created_by_id" = 9999 WHERE "id" = 14;
```
(replacing 9999 with your user id)

are there any scoresets created by you to show in the dashboard? there aren't any in my local dev db

**Comment by EstelleDa** [comment]
I created a test score set and it doesn't appear on my dashboard. But remove `join(ScoreSet.target_genes)` from `query` the score set appears. 

Btw, can you see any score set on mavedb.org dashboard?  Alan and I can't see any score set in there that's why I start from main branches. Hope I don't lead to a wrong direction.

**Comment by ashsny** [comment]
Could you try doing what I did in your dev environment and settings some scoresets to be created by you? 

Can you also confirm your git status for your dev environment reads
```
On branch main
Your branch is up to date with 'origin/main'.
```
after a `git pull` for each of `mavedb-api` and `mavedb-ui`

I suspect there is version skew somewhere at play if removing that code makes a difference.

**Comment by EstelleDa** [comment]
It's very interesting. After following your instruction, I can see those score sets on my dashboard. However, after creating a new score set, it still doesn't appear on dashboard no matter it's published or not. 

I agree removing that join condition will lead to other problem.

**Comment by EstelleDa** [comment]
The target gene doesn't save correctly in creating a new score set. They're None value no matter clicking Add Target button or not. That's why removing `join(ScoreSet.target_genes)` works.

**Comment by nickzoic** [comment]
Yep, confirmed.  A scoreset with no target_gene isn't displayed in the dashboard view, and an experiment with no displayed scoresets is also not displayed.  very likely changing that to `join(ScoreSet.target_genes, isouter=True)` will fix this, as that will get sqlalchemy to do a left join.

This isn't necessarily a bug if all scoresets are required to have at least one target_gene, but currently you can create scoresets with no target_gene, and it seems like it'd be a harmless fix.

**Comment by bencap** [comment]
Score sets are now unable to be created without target genes. Closing this
