### ISSUE TITLE
Looking up Target Accession/Transcript Identifier is slow (hgvs.dataproviders.uta.connect)

### ISSUE THREAD

**Issue by nickzoic** [VariantEffect/mavedb-api#112]
When setting up a Target w/ Genomic Coordinates, you can select "HGNC Name" and then "autocomplete by HGNC" and then when you go to fill in the 
"Accession/Transcript Identifier" it hits `/api/v1/hgvs/transcript/gene/ADC` every time you press a key.  This is pretty slow (250ms in production, 2000ms on my development machine for some reason)

![image](https://github.com/VariantEffect/mavedb-api/assets/1487686/5e5fe008-a11e-4566-873d-1fbeff70d662)

This calls `hgvs.dataproviders.uta.connect().get_gene_info(gene)` which connects to an external postgres server, probably why it's so much slower at home.  The individual get_gene_info lookups are relatively fast but the connect() step is quite slow from here.

Possible solutions:

* the front-end should call this endpoint once when you select the tab, not once for every key you press, since the call doesn't actually depend on what you've typed anyway.

and/or

* the back-end should cache responses from UTA, or at least cache connections, or have its own copy of the database.

**Comment by bencap** [comment]
Completed via VariantEffect/mavedb-ui#105.
