### ISSUE TITLE
504 Gateway Timeout for Large Score Sets

### ISSUE THREAD

**Issue by jarbesfeld** [VariantEffect/mavedb-api#123]
Hi, I'm attempting to load score set urn:mavedb:00000053-a-1 using the `scores` [endpoint](https://api.mavedb.org/docs#/score%20sets/get_score_set_scores_csv_api_v1_score_sets__urn__scores_get) and am getting a 504 Gateway Time-out Error. This is a very large score set (~648,000 variants), and I have not seen this error occur when trying to access smaller score sets.

**Comment by jstone-uw** [comment]
Thanks for the report, @jarbesfeld. We're looking at the API endpoints for downloading score set CSVs, and I suspect that using stream-oriented queries (server-side database cursors, really) will address this issue. If so, we may be able to get the site updated shortly after the holiday.

In the meantime, I'm happy to export some individual data sets if it would help with your work.

—Jeremy

**Comment by jarbesfeld** [comment]
Thank you @jstone-uw! Would you be able to export score set urn:mavedb:00000053-a-1?

**Comment by jstone-uw** [comment]
Sure, here's a Zip file containing scores and counts:
[00000053-a-1.zip](https://github.com/VariantEffect/mavedb-api/files/13746791/00000053-a-1.zip)

**Comment by jarbesfeld** [comment]
Hi, I was wondering what the status is regarding the CSV download endpoint for large score sets?

**Comment by bencap** [comment]
Updates on this will be via #192.
