### ISSUE TITLE
Not possible to add mixed target types to sequence based scoresets

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-api#139]
When adding a new scoreset, if you specify an `hgvs_nt` column it currently isn't possible to add any protein targets if you add a nucleotide target. Having mixed targets will result in a `ValueError: invalid target sequence type for 'hgvs_nt'`.

You should only need to include at minimum 1 nucleotide target if you have an `hgvs_nt` column; as long as you have that the column should be validated.

**Comment by jstone-uw** [comment]
(This was moved to Done status on 2024-03-26 in our GitHub project, but GitHub repo issues don't currently get closed when their project status changes.)
