### ISSUE TITLE
Explore Using CDOT Exclusively as our Sequence Provider

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-api#145]
Various aspects of SeqRepo make it difficult to work with:
- Some Ensembl transcripts return the entire reference sequence for a gene, rather than just the coding sequence. This complicates variant validation for end users who expect to be validating against just the coding sequence.
- Seqrepo has a limited repository of sequences that it is able to provide (what is in UTA. This is a high bar and lacks many past versions of sequences). CDOT provides many more transcripts, in addition to providing versioning information.
- It is very problematic to add custom data to Seqrepo. Because CDOT is based off indexed FASTA files, we could more easily provide our own transcript data if we ever needed to support additional transcripts.

CDOT provides a more consistent interface across transcript type, version, and provenance. We would also be able to simplify our deployment stack, eliminating the SeqRepo Docker container. The one limitation here would be losing access to some other less common genomic builds- right now our CDOT instance is only pulling GRCh37 and 38 data. However, if we did end up needing other transcript data we could add those in as needed.

**Comment by jstone-uw** [comment]
Released in version 2024.0.0 on 2024-04-15.
