### ISSUE TITLE
Useful Failure Responses for Publication Identifier Fetches during Score Set and Experiment Creation

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-api#146]
When adding publication identifiers to Experiments and Score sets, MaveDB checks the bioRxiv, medRxiv, and PubMed servers to try and resolve publication identifier(s) provided with the object we are creating. If the article cannot be found, we should raise an error when trying to create the Experiment / Score set.

**Comment by nickzoic** [comment]
somewhat addressed by 31246a7 although a lot of detail could get added.

**Comment by jstone-uw** [comment]
(This was moved to Done status on 2024-02-27 in our GitHub project, but GitHub repo issues don't currently get closed when their project status changes.)
