### ISSUE TITLE
Downloaded file names

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#154]
When the URNs are converted into file names as part of the CSV download, the `:` is replaced with a literal space. It seems like replacing them with `-` would be better since dealing with spaces on unix file systems is sometimes annoying.

**Comment by EstelleDa** [comment]
It's a UI side problem. I post it again in mavedb-ui [https://github.com/VariantEffect/mavedb-ui/issues/137](https://github.com/VariantEffect/mavedb-ui/issues/137).

**Comment by EstelleDa** [comment]
In main branch, download file name has been changed to _. I'll delete my pull request.

**Comment by bencap** [comment]
Closing this as completed.
