### ISSUE TITLE
Deletion of unpublished score set/experiment fails sometimes.

### ISSUE THREAD

**Issue by jstone-uw** [VariantEffect/mavedb-api#161]
This problem has been reported by one user. We have not been able to reproduce it yet, and perhaps it has already been addressed. This issue should remain open until we are confident that there is no remaining issue.

**Comment by jstone-uw** [comment]
This was addressed on March 4 via a manual fix (addition of an index on `mapped_variants.variant_id`). The issue remains open until the code change is released and the manually-created index is replaced by one generated by an Alembic migration.

**Comment by bencap** [comment]
Released in https://github.com/VariantEffect/mavedb-api/releases/tag/v2024.1.0
