### ISSUE TITLE
Bug from api/v1/publication-identifiers/search/{db_name}/{identifier}

### ISSUE THREAD

**Issue by EstelleDa** [VariantEffect/mavedb-api#235]
Testing identifiers are 21464309 and 23376099, and db_name is PubMed.
I think it links to `search_publications_by_identifier_and_db`. 

![image](https://github.com/VariantEffect/mavedb-api/assets/8445097/a912f8c7-1ccd-4df5-b850-3e693d74c3c5)

Online MaveDB get the same error message:
<img width="592" alt="image" src="https://github.com/VariantEffect/mavedb-api/assets/8445097/51795ed4-314d-4e7d-a732-df94add6f7bf">

**Comment by bencap** [comment]
Released w/ 2024.2.1
