### ISSUE TITLE
Can't get any result if score set urn has space in the end

### ISSUE THREAD

**Issue by EstelleDa** [VariantEffect/mavedb-api#237]
In Search page, users can't get any result if score set urn has space in the end. Example searching text is "urn:mavedb:00000002-a-1 "
<img width="1302" alt="image" src="https://github.com/VariantEffect/mavedb-api/assets/8445097/f120f270-30db-4db1-a06c-29243467b729">

**Comment by bencap** [comment]
Released w/ 2024.2.1
