### ISSUE TITLE
Scoreset stuck at "being processed"

### ISSUE THREAD

**Issue by kaiyuegithub** [VariantEffect/mavedb-api#249]
The tep scoresets are stuck for 1 day at: 
"Scores and/or counts are being processed. Refresh this page in a few minutes to check on their status."

Unable to publish.

Here are the links to the tmp scoresets:
https://www.mavedb.org/score-sets/tmp:55aba8dd-6c4c-4242-ad78-237421e618b8
https://www.mavedb.org/score-sets/tmp:9ccbc1f6-bf3b-4bc5-8489-70e531f97ec9

**Comment by bencap** [comment]
@EstelleDa We might consider changing that function call to:
```
ingested_df = pd.read_csv(
        filepath_or_buffer=file_data,
        sep=",",
        encoding="utf-8",
        index_col=False,
        quotechar="'",
        na_values=extra_na_values,
        keep_default_na=True,
        dtype={**{col: str for col in HGVSColumns.options()}, "scores": float},
    )
```

By passing `index_col` as `False` we avoid inferring that `hgvs_nt` is the index col and are then able to use `Table_S2.csv` directly and pass variant validation. I doubt anyone is using a legitimate index column in their data tables. More likely, the first column in a user provided table should be treated as data.
