### ISSUE TITLE
Investigate Taxonomy Key Error

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-api#266]
Investigate the cause of https://brotmanbaty.slack.com/archives/C055J69KT1T/p1724235142852629

Raised at
https://github.com/VariantEffect/mavedb-api/blob/baddfe8cccb02619455aec9e66b33370d6e15724/src/mavedb/lib/taxonomies.py#L41

**Comment by EstelleDa** [comment]
Type 20111 in the Taxonomy field can reproduce this problem. 
Response data from NCBI is {"taxonomy_nodes":[{"errors":[{"reason":"The taxonomy name you specified (20111) is not a recognized NCBI Taxonomy name.", "invalid_identifiers":["20111"]}], "query":["20111"]}]} and the response status code is 200.
