### ISSUE TITLE
Update Project Dependencies

### ISSUE THREAD

**Issue by bencap** [VariantEffect/mavedb-api#274]
Dependabot messages have gotten more frequent, and there are now a few dependencies with high severity. We should refresh these in particular.

**Comment by DM0815** [comment]
when I conduct install code: pip install mavedb, it reminds that Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-_076n957/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-_076n957/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-_076n957/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-_076n957/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-_076n957/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.  
Can you give me some suggestions? Thanks.
