### ISSUE TITLE
MaveDB IDs are reported using the tmp: namespace

### ISSUE THREAD

**Issue by jarbesfeld** [VariantEffect/mavedb-api#326]
When running queries using the /scores endpoint, a MaveDB ID starting with the prefix `tmp:` is reported. I believe the prefix should be urn:mavedb:{score set number)#{variant number)

**Comment by bencap** [comment]
Thanks for reporting @jarbesfeld. we have this planned as part of #281 and should get to it within a couple of weeks.

**Comment by bencap** [comment]
Closing as a duplicate of #281, this issue can be tracked using that issue page.
