### ISSUE TITLE
Target sequence categories

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#35]
The target category names are not very API-like. I propose changing them to "protein_coding" "regulatory" and "other_noncoding" for their internal representation and using the text provided in the UI.

https://github.com/VariantEffect/mavedb-api/blob/61c3114c1197f27b5ed68c5c91091546c9f70238/src/mavedb/lib/validation/constants/target.py#L1

**Comment by bencap** [comment]
Note we will need to adjust mapper return values, and double check how front end code is displayed.
