### ISSUE TITLE
Download all file

### ISSUE THREAD

**Issue by DM0815** [VariantEffect/mavedb-api#351]
I want to know is there any quick way to download scoresert of all the datasets directly according to urn id or uniprot id? Because I plan to use the dataset to train a deep learning model.

Thanks.

**Comment by afrubin** [comment]
To support this use case, MaveDB has a versioned archive on Zenodo, available at the following DOI https://doi.org/10.5281/zenodo.11201736

**Comment by DM0815** [comment]
> To support this use case, MaveDB has a versioned archive on Zenodo, available at the following DOI https://doi.org/10.5281/zenodo.11201736

Thank you for your reply, much appreciated.
