### ISSUE TITLE
Target sequence nomenclature

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#36]
The MaveDB API uses the now-outdated term `wt_sequence` instead of `target_sequence` inside the models.

This should be updated to use the more generic `target_sequence` throughout the codebase, since many of the target sequences in the database are not "wild type" in that they don't occur naturally.

**Comment by afrubin** [comment]
A related issue is that we use the term `target_gene` for the target, and this is not always a gene (it might be a noncoding element like an enhancer).

**Comment by bencap** [comment]
Completed via #60.
