### ISSUE TITLE
Generating clinical variant IDs

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#42]
MaveDB defines each variant with respect to the target sequence provided by the uploader. This is often a cDNA or a part of a gene or protein sequence. In order to share our variants with other resources, we will need to generate variant strings with respect to a reference genome.

The proposed solution for human target sequences is to generate an HGVS string relative to hg38 and use those HGVS strings to generate CAids from the [ClinGen Allele Registry](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing).

Variants in MaveDB will be individually addressable by CAid.

We will need to verify the target accession numbers for existing datasets and make sure that the target sequences match the reference. Datasets that do not have suitable accession numbers or that do not match the reference will be flagged for followup.

**Comment by afrubin** [comment]
We have changed the way that we're going to address this issue. Instead of relying primarily on CAid, we are going to compute and store [GA4GH VRS objects](https://vrs.ga4gh.org/en/stable/) in MaveDB, which can be consumed by ClinGen and other partners.

We should still store relevant identifiers like CAid in the database and respond to API queries using these terms, but the way we are computing and storing the underlying information is different.

The prototype mapping method including a download link for the VRS objects is available in [this repository](https://github.com/ave-dcd/dcd_mapping).

**Comment by afrubin** [comment]
For the first implementation of this, let's keep things simple.

We want to add a new mapped_variant table and model that stores the ID in the variant table, the JSON for the pre-mapped variant, and the JSON for the post-mapped variant.

The data from the DCD mapping work linked above will be loaded as a one-off, and we'll add a process for ingesting future datasets via the API later.

Mapped variants should be accessible via the API when the user provides a MaveDB variant URN.

**Comment by EstelleDa** [comment]
https://github.com/VariantEffect/mavedb-api/tree/mappedVariant
This is a simple mapped variant model branch.

**Comment by afrubin** [comment]
@EstelleDa in addition to allowing users to access one variant at a time by API, we should also let them download a file containing all the mapped variants for each score set that has them. Can you implement this and add it to your branch?

**Comment by EstelleDa** [comment]
https://github.com/VariantEffect/mavedb-ui/tree/downloadMappedVariantsFile
Mavedb-ui branch is here.
