### ISSUE TITLE
API exposing internal id values

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#44]
The API is returning the internal id field used in the database. We don't want people to rely on this being stable, so it should probably be removed from the response.

This seems to be the case for most (all?) models, including simple models like raw reads identifier and larger models like experiments.

**Comment by jstone-uw** [comment]
I don't think this is actually the case for records that have URNs (experiment sets, experiments, and scoresets) or identifier strings (like target gene identifiers).

IDs are exposed for other model objects that are presented in drop-down lists, for instance during score set creation. But there's no presumption that these IDs are stable.

**Comment by afrubin** [comment]
OK, so if I understand correctly including the internal ids in the API output is an important implementation detail for the UI. I'll go ahead and close this and we can document that users should not expect any of the "id" fields to be stable over time.
