### ISSUE TITLE
Inconsistent API endpoint capitalization

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#45]
The valid API endpoints for experiment set and score set records are `experimentSets` and `scoresets`, respectively.

We should make the case of these consistent. My preference is for all lowercase but either is fine.

I think this new API endpoint is so new that we don't need to worry about making this change backwards-compatible.

**Comment by jstone-uw** [comment]
All of the API endpoints use camelCase -- which I realize isn't very Pythonic. I'd actually prefer kebab-case for URL elements, with JSON property names remaining in camelCase.

'Scoreset' is used throughout as if it were a single word, which is an inheritance from the Django version. We could refactor this throughout, with priority going to things exposed in the API (endpoint names and view model properties).

**Comment by afrubin** [comment]
> All of the API endpoints use camelCase -- which I realize isn't very Pythonic. I'd actually prefer kebab-case for URL elements, with JSON property names remaining in camelCase.

kebab-case for URL and camelCase for property names sounds good to me. Let's make that change sooner rather than later before people get used to the current conventions.

> 'Scoreset' is used throughout as if it were a single word, which is an inheritance from the Django version. We could refactor this, with priority going to things exposed in the API (endpoint names and view model properties).

I think we should do this refactoring, particularly for external facing things.
