### ISSUE TITLE
Add contributor information

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#57]
In the previous version of MaveDB, datasets could have multiple contributing users listed. This was important for managing access permissions for private datasets, but it was also a valuable record of who contributed to the curation of the various entries.

It seems like this information, as well as the ability to add additional contributors to a dataset, may have been lost in the transition from Django to FastAPI.

It's probably not necessary to re-implement the admin/editor/viewer roles, but uploaders should be able to add other MaveDB users to the records they create and have that information be displayed. Once a secondary user has been added, it's fine if they have full edit privileges over the dataset if that makes the implementation easier.

Once this feature is added, we'll need to repopulate the extra contributors from the last backup of the Django database if those tables weren't retained in the current version.

**Comment by ashsny** [comment]
For now, deleting contributor role documentation.
