### ISSUE TITLE
Score sets with multiple targets

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#59]
Researchers are starting to do more experiments that mix variants from multiple target sequences into a single population. To support this, we'll need to make some changes to our data model and validation. Currently this can only be done by having a single experiment with a different score set for each target.

One possible solution is to allow multiple `target_gene` objects to be attached to a single score set. If multiple target genes are present, all variants in the score and count tables will be required to have an identifier specified (e.g. `"TargetA:p.Asp12Ala"` where `TargetA` is the identifier). This syntax is already supported by mavehgvs, so adding this feature to the validation should be fairly straightforward. We will need to have users define the identifier for each target gene, which would be a new field.

Suggestions for alternate ways to implement this are welcome.

**Comment by bencap** [comment]
Already completed as part of #60
