### ISSUE TITLE
Score sets with genomic coordinates and no target

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#60]
To better support saturation genome editing (SGE) data and also support base editor/prime editing screens, we should add a new type of score set that doesn't require the user to upload a target sequence and instead includes fully-qualified genomic coordinates for the variants.

The variants should still use mavehgvs-style strings, but include a prefix that is either a fully-qualified chromosome or a transcript identifier from RefSeq, with version number (e.g. [NC_000012.12](https://www.ncbi.nlm.nih.gov/nuccore/NC_000012.12) for chr12 or [NM_007294.4](https://www.ncbi.nlm.nih.gov/nuccore/NM_007294.4) for the BRCA1 transcript sequence). Protein identifiers and datasets with only protein variants would not be permitted.

This will require implementing a genome-aware validation process on the server. We can use an existing software tool for this function:
* [VariantValidator](https://variantvalidator.org/)
* [TransVar](https://transvar.readthedocs.io/en/latest/)
* [Biocommons HGVS](https://github.com/biocommons/hgvs)
* and many more?

We can implement this as either a special case of score set, or as a new type of score set entirely. It's worth thinking through the implications of each of these approaches.

It should also be possible to create a meta-analysis score set of this type that is based on one or more "normal" score sets that contain target sequences. I think this will have a lot of utility for clinically-focused re-annotation of existing MAVE data.

**Comment by jstone-uw** [comment]
(This was moved to Done status on 2024-01-24 in our GitHub project, but GitHub repo issues don't currently get closed when their project status changes.)
