### ISSUE TITLE
Missing .env.prod File?

### ISSUE THREAD

**Issue by brucejwittmann** [VariantEffect/mavedb-api#69]
I am trying to use the mavedb-api for the first time (so there's a good chance I'm doing something wrong here), and am running into the below error:

```
(mavedb) bwittmann@bruce-ubuntu:~/GitRepos/mavedb-api$ sudo docker-compose -f docker-compose-prod.yml up
ERROR: Couldn't find env file: /home/bwittmann/GitRepos/mavedb-api/settings/.env.prod
```

Is the `env.prod` file supposed to come with the repository, or is this something that I should be configuring myself? The docker build command completed without issue before trying to run with `docker-compose`.

**Comment by afrubin** [comment]
@brucejwittmann You'll need to copy the `settings/.env.template` file to create a local copy of `settings/.env.prod` (or `settings/.env.dev` for the dev deployment). You can then customize it accordingly, but it should work out of the box.

We'll add a note about this in the documentation, so thanks for bringing this to our attention!

Let us know if you run into any other issues.

**Comment by brucejwittmann** [comment]
Thanks, @afrubin! That makes sense.
