### ISSUE TITLE
Admin users

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#76]
The server enforces several sensible constraints on who can add things on contribute to various records (e.g., only the owner can create a new experiment under an existing experiment set). There are circumstances where an admin user would want to violate these constraints and we should have a mechanism for doing so.

However, since users are authenticated using ORCID, it doesn't make sense to me to have multiple accounts (and therefore multiple ORCID profiles) per person. It also seems dangerous and error-prone for a user to always have admin privileges - I'm adding data as a normal user most of the time, and these safeguards are helpful in preventing me from uploading something incorrectly.

My proposed solution is to handle the admin status of a user by issuing multiple API keys per user - a normal key and an admin key. Actions that require admin privileges would need to provide the admin key. This would be selectable as a toggle in the profile on the website, and copyable for using the API directly.

From the UI side, if the user is logged in as admin, they should get a thin, easily noticeable banner at the top of the page warning them that they have admin privileges enabled. Buttons that interact with the API could also change color to make sure that it's clear this change is being done as an admin.

From the API side, this might require changing the current code that gets a user, since I think it mostly just resolves by user id (ORCID number) and expects a single row. These instances would have to be wrapped with a new function, and the permissions model would have to be updated to accept certain changes from admin users.

The two added benefits of doing this as API keys are that changes will be associated with the admin user's primary account (since we track modifications by ORCID) and that it should be straightforward to add additional levels of admin privileges if we decide we want more fine-grained control in the future.

Please weigh in if you have thoughts on how to do this - I'm sure it's a solved problem that I just haven't encountered before.

In the meantime, I will add additional tests to make sure we're enforcing more things that normal users can't do, but that we want admin users to be allowed to do.

**Comment by bencap** [comment]
Released in https://github.com/VariantEffect/mavedb-api/releases/tag/v2024.1.0
