### ISSUE TITLE
Storing and searching on publication data

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb-api#9]
Users should be able to search for MaveDB entries based on the authors on the associated publications. Currently the only people associated with a given record are the people who were involved in the upload, which has limited utility.

Other fields associated with the publications should also be available to search, such as title, abstract, year range, etc. We should store all the metadata from the PubMed/preprint records locally and make it available for search using the website search page or API.

**Comment by bencap** [comment]
Additional publication data (title, abstract, publication year, doi, journal) are stored as of #65.
