### ISSUE TITLE
Asynchronous score set ingestion

### ISSUE THREAD

**Issue by jstone-uw** [VariantEffect/mavedb-api#90]
Score sets are currently ingested synchronously, which has two disadvantages:
- It forces the user to wait for an unknown period of time, and
- It may impose undesirable load on the API.

The original Django version of MaveDB ingested scores asynchronously. We made the choice to use synchronous ingestion as a first step in the new version, but the mechanism for loading asynchronous data is still partly present. Since larger score sets are likely to be loaded more often in the future (including large score sets that have genomic references), restoring asynchronous ingestion may be appropriate now.

**Comment by jstone-uw** [comment]
This will entail a change in usage pattern for API users, who will have to poll the server to determine when a score set is ready for use.

**Comment by nickzoic** [comment]
Agreed.  In the meantime we should remove files:

* `src/mavedb/models/failed_task.py`
* `src/mavedb/lib/worker.py`
* `src/mavedb/tasks/scoreset_tasks.py`

which are no longer used.

**Comment by jstone-uw** [comment]
From the description of duplicate issue #160:

In support of issues like https://atlasofvarianteffect.slack.com/archives/C06A73QAFK4/p1709230987644889, we should handle variant additions to score sets via some sort of worker process handled asynchronously to score set creation.

Completion of this task would also involve setting up a new worker service for MaveDB and enabling it to handle async creation of variants. Any errors during variant creation should be served to the user on the score set page.

**Comment by jstone-uw** [comment]
Released in version 2024.0.0 on 2024-04-15.
