### ISSUE TITLE
Smaller API responses for score and count previews

### ISSUE THREAD

**Issue by jstone-uw** [VariantEffect/mavedb-api#92]
To display a preview of scores and counts in a score set, the UI currently fetches `/api/v1/score-sets/{urn}/scores` and `/api/v1/score-sets/{urn}/counts`. These endpoints return complete score and count data, but we only need a small number of rows for the preview. Pagination parameters should be added so that the client can request something like `/api/v1/score-sets/{urn}/scores?start=0&limit=100`.

**Comment by EstelleDa** [comment]
@jstone-uw I created a branch for this one and merging it to main branch needs at least one reviewer to approve. Let me know if anything you wanna change to it.
